apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-svc
  labels:
    app: notify-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify-svc
  template:
    metadata:
      name: notify-svc
      labels:
        app: notify-svc
    spec:
      containers:
        - name: notify-svc
          image: julioh/notify-svc
          imagePullPolicy: Never
          env:
            - name: RabbitMq__Host
              value: rabbit-clusterip
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: notify-secret
                  key: rabbitUn
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: notify-secret
                  key: rabbitPw
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notify-clusterip
spec:
  selector:
    app: notify-svc
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
