name: deploy-identity

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
    paths:
      - 'src/IdentityServer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/IdentityServer/Dockerfile
          push: true
          tags: julioh/identity-svc:latest